name: Auto Assign New Pull Requests to Project(s)

on:
  pull_request:
    types: [opened]

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Add new pull requests to org Protocol Design project
    steps:
      - uses: alex-page/github-project-automation-plus@50502d399cbb98cefe7ce1f99f93f78c6756562e
        with:
          project: Protocol Design (Team Board)
          column: In progress
          repo-token: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}

