---

name: "Add IPRs To Project Board"

"on":
  pull_request:
    types:
      - opened
env:
  GH_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
  PROJECT_ID: ${{ secrets.PROTOCOL_DESIGN_PROJECT_ID }}
  PR_ID: ${{ github.event.pull_request.node_id }}
  USER: ${{ github.actor }}

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Add pr to project board"
        run: |
          gh api graphql -f query='
            mutation($user:String!, $project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {clientMutationId: $user, projectId: $project, contentId: $pr}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID -f user=$USER
