---


name: "Quality checks"

"on":
  pull_request:
    branches:
      - master
      - cosmicelevator
      - palazzomistero

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run Yamllint"
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .github/workflows/config/yamllintconfig.yml

  spellcheck:
    name: "Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run PySpelling"
        uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          task_name: Markdown

  markdownlint:
    name: "Markdownlint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run Markdownlint"
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .github/workflows/config/markdownlint.json
          ignore_path: .github/workflows/config/markdownlintignore

  checkcodes:
    name: "Approbation"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3.5.3

      - name: "Run Check AC codes"
        run: |
          npx github:vegaprotocol/approbation check-codes --specs="{./non-protocol-specs/**/*.md,./protocol/**/*.md,./protocol/**/*.ipynb}"

      - name: "Run Check file names"
        run: |
          npx github:vegaprotocol/approbation check-filenames --specs="{./non-protocol-specs/**/*.md,./protocol/**/*.md,./protocol/**/*.ipynb}"

      - name: "Run Check Features"
        run: |
          npx github:vegaprotocol/approbation check-features --specs="{./non-protocol-specs/**/*.md,./protocol/**/*.md,./protocol/**/*.ipynb}" --features="./protocol/features.json"
