---


name: "Quality checks"

"on":
  pull_request:
    branches:
      - master
      - cosmicelevator
      - palazzomistero

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Run Yamllint"
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .github/workflows/config/yamllintconfig.yml

  spellcheck:
    name: "Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Run PySpelling"
        uses: rojopolis/spellcheck-github-actions@0.24.0
        with:
          task_name: Markdown

  markdownlint:
    name: "Markdownlint"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Run Markdownlint"
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: .
          config_file: .github/workflows/config/markdownlint.json
          ignore_path: .github/workflows/config/markdownlintignore

  checkcodes:
    name: "Approbation"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run Check AC codes"
        run: |
          docker run -it -v $PWD:/workspace ghcr.io/vegaprotocol/approbation:main check-filenames --specs="{/workspace/non-protocol-specs/**/*.md,/workspace/protocol/**/*.md}"

      - name: "Run Check file names"
        run: |
          docker run -it -v $PWD:/workspace ghcr.io/vegaprotocol/approbation:main check-codes --specs="{/workspace/non-protocol-specs/**/*.md,/workspace/protocol/**/*.md}"